version: "3.9"
services:
  streamlit:
    build: .
    container_name: churn_dashboard
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: streamlit run src/app_streamlit.py --server.port=8501 --server.address=0.0.0.0 
  prefect:
    build: .
    container_name: churn_pipeline
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: prefect deployment run "src.pipeline.main_flow/run"streamlit --version